### ISSUE TITLE
meanExpand and meanContract html problem

### ISSUE THREAD

**Issue by vincentkedison** [meanthemes/meanMenu#65]
I recently try to use meanmenu.
When I try to use font awesome icon for meanExpand character, this problem occurs.

``` javascript
jQuery('nav.main-menu').meanmenu({
            meanMenuClose: '<i class="fa fa-times"></i>', // single character you want to represent the close menu button
            meanExpand: '<i class="fa fa-angle-down"></i>', // single character you want to represent the expand for ULs
            meanContract: "-", // single character you want to represent the contract for ULs
            meanMenuContainer: '#responsive-menu-container', // Choose where meanmenu will be placed within the HTML
            meanScreenWidth: "767", // set the screen width you want meanmenu to kick in at
            meanRemoveAttrs: true // true to remove classes and IDs, false to keep them
        });
```

The icon loaded perfectly in the begining.
![initial](https://cloud.githubusercontent.com/assets/7263785/17209637/4c548ab4-54e8-11e6-9266-54f9b0ed9438.PNG)

But when I expand the product menu and collapse it, the icon become like this
![error](https://cloud.githubusercontent.com/assets/7263785/17209636/4c4e25f2-54e8-11e6-8dae-6fcb9a6d0f71.png)

This problem also happen for the meanContract.

Please help. Thankyou

**Comment by Ansif** [comment]
Hi, @vincentkedison!

In [jquery.meanmenu.js](https://github.com/meanthemes/meanMenu/blob/master/jquery.meanmenu.js#L193) Line number 193. You'll see : jQuery(this).text(meanExpand);
Instead of that .text method please use .html
Like jQuery(this).html(meanExpand);

Also, in 196 line number - you'll see : jQuery(this).text(meanContract);
Instead of .text use .html. Like jQuery(this).html(meanContract);

👍

**Comment by meanthemes** [comment]
Thanks @Ansif - we're in the process of rewriting MeanMenu to make things like this a little bit easier
